### ISSUE TITLE
Any have sample to using it ?

### ISSUE THREAD

**Issue by mazharrasyad** [2amigos/yii2-google-maps-library#120]
I found sample how to use this extension in : http://techbloghunting.com/2017/05/27/yii2-google-maps-api/

But not everything works only a few, for that I ask for help how to use this extension because I still new using framework yii2. Thanks for the reply and sorry for my bad english

**Comment by Animalejourbano** [comment]
I can't get that example to work, but if instead of using de "Asset Bundle Customization" part you simple put in the return array on /config/params.php

`'googleMapsApiKey' => 'your_google_maps_key',`
`'googleMapsLibraries' => '3.33',`
`'googleMapsLanguage' => 'en',`

The rest of the example works, at least the simple map with marker, that's what I'm using.

**Comment by mazharrasyad** [comment]
Ok, thanks for the response
